name: Black

on:
  push:
  pull_request:
  merge_group:

jobs:
  black:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -e .

      - name: Reformat the code with black
        run: |
          black gwemopt --check
