name: Run isort

on:
  push:
  pull_request:
  merge_group:

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
          pip install -e .

      - name: Reformat the code with isort
        run: |
          isort . --diff
